Repository Ximena1998/Xodim, pull requests merged in 2020-07, with the labels that each got.

#5 heroku
  xidomin/settings.py
Labels: Prioridad 2

#8 Test de Sintomatologia
  xidomin/settings.py
Labels: Prioridad 2

#21 Correcion BD
  xodin/settings.py
Labels: Prioridad 2

#22 implementacion de autentificacion para acceso a ciertas urls
  aplicaciones/principal/__pycache__/class_view.cpython-38.pyc
  aplicaciones/principal/__pycache__/decorators.cpython-38.pyc
  aplicaciones/principal/__pycache__/urls.cpython-38.pyc
  aplicaciones/principal/__pycache__/views.cpython-38.pyc
  aplicaciones/principal/class_view.py
  aplicaciones/principal/urls.py
  aplicaciones/principal/views.py
  templates/index.html
Labels: Prioridad 2

#23 Correción Modelo
  aplicaciones/__pycache__/__init__.cpython-37.pyc
  aplicaciones/principal/__pycache__/admin.cpython-37.pyc
  aplicaciones/principal/__pycache__/class_view.cpython-37.pyc
  aplicaciones/principal/__pycache__/forms.cpython-37.pyc
  aplicaciones/principal/__pycache__/models.cpython-37.pyc
  aplicaciones/principal/__pycache__/urls.cpython-37.pyc
  aplicaciones/principal/__pycache__/views.cpython-37.pyc
  aplicaciones/principal/forms.py
  aplicaciones/principal/migrations/0001_initial.py
  aplicaciones/principal/migrations/0002_auto_20200712_1943.py
  aplicaciones/principal/migrations/0002_horario.py
  aplicaciones/principal/migrations/0003_auto_20200707_1348.py
  aplicaciones/principal/migrations/0003_auto_20200712_1949.py
  aplicaciones/principal/migrations/__pycache__/0001_initial.cpython-37.pyc
  aplicaciones/principal/migrations/__pycache__/0002_auto_20200712_1943.cpython-37.pyc
  aplicaciones/principal/migrations/__pycache__/0002_horario.cpython-37.pyc
  aplicaciones/principal/migrations/__pycache__/0003_auto_20200707_1348.cpython-37.pyc
  aplicaciones/principal/migrations/__pycache__/0003_auto_20200712_1949.cpython-37.pyc
  aplicaciones/principal/migrations/__pycache__/0004_auto_20200712_1841.cpython-37.pyc
  aplicaciones/principal/migrations/__pycache__/__init__.cpython-37.pyc
  aplicaciones/principal/models.py
  xodin/__pycache__/__init__.cpython-37.pyc
  xodin/__pycache__/settings.cpython-37.pyc
  xodin/__pycache__/urls.cpython-37.pyc
  xodin/__pycache__/wsgi.cpython-37.pyc
  xodin/settings.py
Labels: Prioridad 3

#25 ventanas emergentes
  aplicaciones/principal/__pycache__/class_view.cpython-38.pyc
  aplicaciones/principal/__pycache__/urls.cpython-38.pyc
  aplicaciones/principal/__pycache__/views.cpython-38.pyc
  static/js/funciones.js
  templates/index.html
Labels: Prioridad 3

#24 Realizacion de graficos estadisticos
  aplicaciones/principal/__pycache__/class_view.cpython-37.pyc
  aplicaciones/principal/__pycache__/forms.cpython-37.pyc
  aplicaciones/principal/__pycache__/models.cpython-37.pyc
  aplicaciones/principal/__pycache__/views.cpython-37.pyc
  aplicaciones/principal/class_view.py
  aplicaciones/principal/migrations/__pycache__/0001_initial.cpython-37.pyc
  aplicaciones/principal/migrations/__pycache__/0002_auto_20200712_1943.cpython-37.pyc
  aplicaciones/principal/migrations/__pycache__/0003_auto_20200712_1949.cpython-37.pyc
  aplicaciones/principal/views.py
  templates/estadisticas.html
  xodin/__pycache__/settings.cpython-37.pyc
  xodin/settings.py
Labels: Prioridad 3

#26 diseño
  aplicaciones/principal/__pycache__/class_view.cpython-38.pyc
  aplicaciones/principal/__pycache__/forms.cpython-38.pyc
  aplicaciones/principal/__pycache__/models.cpython-38.pyc
  aplicaciones/principal/__pycache__/urls.cpython-38.pyc
  aplicaciones/principal/__pycache__/views.cpython-38.pyc
  aplicaciones/principal/class_view.py
  aplicaciones/principal/migrations/__pycache__/0001_initial.cpython-38.pyc
  aplicaciones/principal/migrations/__pycache__/0002_auto_20200712_1943.cpython-38.pyc
  aplicaciones/principal/migrations/__pycache__/0003_auto_20200712_1949.cpython-38.pyc
  aplicaciones/principal/urls.py
  static/css/main.css
  static/css/util.css
  static/images/bg-01.jpg
  static/images/icons/favicon.ico
  static/images/signup-bg.jfif
  static/images/signup-bg2.jpg
  static/js/main.js
  static/vendor/animate/animate.css
  static/vendor/animsition/css/animsition.css
  static/vendor/animsition/css/animsition.min.css
  static/vendor/animsition/js/animsition.js
  static/vendor/animsition/js/animsition.min.js
  static/vendor/bootstrap/css/bootstrap-grid.css
  static/vendor/bootstrap/css/bootstrap-grid.css.map
  static/vendor/bootstrap/css/bootstrap-grid.min.css
  static/vendor/bootstrap/css/bootstrap-grid.min.css.map
  static/vendor/bootstrap/css/bootstrap-reboot.css
  static/vendor/bootstrap/css/bootstrap-reboot.css.map
  static/vendor/bootstrap/css/bootstrap-reboot.min.css
  static/vendor/bootstrap/css/bootstrap-reboot.min.css.map
  static/vendor/bootstrap/css/bootstrap.css
  static/vendor/bootstrap/css/bootstrap.css.map
  static/vendor/bootstrap/css/bootstrap.min.css
  static/vendor/bootstrap/css/bootstrap.min.css.map
  static/vendor/bootstrap/js/bootstrap.js
  static/vendor/bootstrap/js/bootstrap.min.js
  static/vendor/bootstrap/js/popper.js
  static/vendor/bootstrap/js/popper.min.js
  static/vendor/bootstrap/js/tooltip.js
  static/vendor/countdowntime/countdowntime.js
  static/vendor/css-hamburgers/hamburgers.css
  static/vendor/css-hamburgers/hamburgers.min.css
  static/vendor/daterangepicker/daterangepicker.css
  static/vendor/daterangepicker/daterangepicker.js
  static/vendor/daterangepicker/moment.js
  static/vendor/daterangepicker/moment.min.js
  static/vendor/jquery/jquery-3.2.1.min.js
  static/vendor/perfect-scrollbar/perfect-scrollbar.css
  static/vendor/perfect-scrollbar/perfect-scrollbar.min.js
  static/vendor/select2/select2.css
  static/vendor/select2/select2.js
  static/vendor/select2/select2.min.css
  static/vendor/select2/select2.min.js
  templates/estadisticas.html
  templates/index.html
  templates/registroEmp.html
  xodin/__pycache__/settings.cpython-38.pyc
  xodin/__pycache__/urls.cpython-38.pyc
  xodin/settings.py
  xodin/urls.py
Labels: Prioridad 3

#27 Formato a forms
  aplicaciones/principal/__pycache__/class_view.cpython-37.pyc
  aplicaciones/principal/__pycache__/forms.cpython-37.pyc
  aplicaciones/principal/__pycache__/views.cpython-37.pyc
  aplicaciones/principal/forms.py
  xodin/__pycache__/settings.cpython-37.pyc
Labels: Prioridad 3

#29 Corección de widgets
  aplicaciones/principal/forms.py
Labels: Prioridad 3

#30 Registro de Horario
  aplicaciones/principal/__pycache__/class_view.cpython-37.pyc
  aplicaciones/principal/__pycache__/forms.cpython-37.pyc
  aplicaciones/principal/__pycache__/urls.cpython-37.pyc
  aplicaciones/principal/__pycache__/views.cpython-37.pyc
  aplicaciones/principal/class_view.py
  aplicaciones/principal/views.py
  templates/formularios
  templates/inicioSesion.html
  xodin/__pycache__/settings.cpython-37.pyc
  xodin/__pycache__/urls.cpython-37.pyc
  xodin/urls.py
Labels: Prioridad 3

#31 Registro de empleados
  Entorno/init/Lib/site-packages/__pycache__/dj_database_url.cpython-38.pyc
  Entorno/init/Lib/site-packages/django_heroku/__pycache__/__init__.cpython-38.pyc
  Entorno/init/Lib/site-packages/django_heroku/__pycache__/core.cpython-38.pyc
  Entorno/init/Lib/site-packages/whitenoise/__pycache__/__init__.cpython-38.pyc
  Entorno/init/Lib/site-packages/whitenoise/__pycache__/base.cpython-38.pyc
  Entorno/init/Lib/site-packages/whitenoise/__pycache__/compress.cpython-38.pyc
  Entorno/init/Lib/site-packages/whitenoise/__pycache__/media_types.cpython-38.pyc
  Entorno/init/Lib/site-packages/whitenoise/__pycache__/middleware.cpython-38.pyc
  Entorno/init/Lib/site-packages/whitenoise/__pycache__/responders.cpython-38.pyc
  Entorno/init/Lib/site-packages/whitenoise/__pycache__/storage.cpython-38.pyc
  Entorno/init/Lib/site-packages/whitenoise/__pycache__/string_utils.cpython-38.pyc
  aplicaciones/principal/__pycache__/urls.cpython-38.pyc
  aplicaciones/principal/__pycache__/views.cpython-38.pyc
  aplicaciones/principal/urls.py
  aplicaciones/principal/views.py
  static/images/photo-1560796952-f1c9b838544c.jfif
  static/images/signup-bg.jfif
  static/images/signup-bg.jpg
  static/images/signup-bg2.jpg
  templates/biometrico_listar.html
  templates/estadisticas.html
  templates/formularios
  templates/index.html
  templates/inicioSesion.html
  templates/registroHorario.html
  templates/reporte_sueldos.html
  xodin/__pycache__/settings.cpython-38.pyc
  xodin/__pycache__/urls.cpython-38.pyc
  xodin/urls.py
Labels: Prioridad 2, Prioridad 4
